---
title: "Analysis of Toronto's Red Light Cameras"
author: Gavin Crooks
date: today
date-format: long
abstract: "Red light Camera's serve a number of uses for the municple governemnt of Toronto.Firstly, they police the roads, creating a safer city. Secondly, they generate revenue for the city. In this paper I analyze the data red light camera data provided by opendatatoronto to determine if red light cameras are effective at either of the reasons listed above."
format: pdf
number-sections: true
bibliography: references.bib 
---
\newpage

```{r}
#| include: false
#| warning: false
#| message: false
library(tidyverse)
library(knitr)
cleaned_data <- read_csv("outputs/Data/analysis_data.csv")
x = sum(cleaned_data$"2022")
x
```



# Introduction

In Toronto the the fine for entering an intersection during a red light, and being caught by a red light camera is 325CAD [@citecity]. This is a very large fine which most would like to avoid however, since 2007 the, red light cameras across the city have issued thousands of tickets [@ODT]. The total number of tickets issued in 2022 was `r x`. 

You can and should cross-reference sections and sub-sections. 

The remainder of this paper is structured as follows. @sec-data....



# Data {#sec-data}


# Discussion

## First discussion point {#sec-first-point}

If my paper were 10 pages, then should be be at least 2.5 pages. The discussion is a chance to show off what you know and what you learnt from all this. 

## Second discussion point

## Third discussion point

## Weaknesses and next steps

Weaknesses and next steps should also be included.

\newpage

\appendix

# Appendix {-}


# Additional data details

# Model details {#sec-model-details}

## Posterior predictive check


\newpage


# References


